default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: app
  username: server
  password: password@123
  host: db
  timeout: 5000

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
